version: '3.1'

services:
  jaeger:
    image: jaegertracing/all-in-one
    ports:
      - 16686:16686
      - 14269:14269
      - 14268:14268
      - 14250:14250

  otel-collector:
    image: otel/opentelemetry-collector
    depends_on:
      - jaeger
    command: [--config=/etc/otel-collector-config.yaml]
    volumes:
      - ./collector-config.yml:/etc/otel-collector-config.yaml
    ports:
      - 4317:4317 # OTLP gRPC receiver
      - 4318:4318 # OTLP http receiver
